/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sunny' at '16-8-21 下午11:33' with Gradle 2.11
 *
 * @author Sunny, @date 16-8-21 下午11:33
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
